import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import barbershopsRouter from "./barbershops";
import barbersRouter from "./barbers";
import servicesRouter from "./services";
import appointmentsRouter from "./appointments";
import productsRouter from "./products";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import verifyEmailRouter from "./verify-email";
import contactRouter from "./contact";
import uploadRouter from "./upload";
import adsRouter from "./ads";
import waitingListRouter from "./waiting-list";
import holidaysRouter from "./holidays";
import couponsRouter from "./coupons";
import loyaltyRouter from "./loyalty";
import recurringRouter from "./recurring";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(barbershopsRouter);
router.use(barbersRouter);
router.use(servicesRouter);
router.use(appointmentsRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(verifyEmailRouter);
router.use(contactRouter);
router.use(uploadRouter);
router.use(adsRouter);
router.use(waitingListRouter);
router.use(holidaysRouter);
router.use(couponsRouter);
router.use(loyaltyRouter);
router.use(recurringRouter);

export default router;
