/**
 * Complete list of Kosovo municipalities (38), sorted alphabetically.
 * Used consistently across all city dropdowns and filters in the app
 * so that values stored in the DB always match filter keys.
 */
export const KOSOVO_CITIES: string[] = [
  "Deçan",
  "Dragash",
  "Drenas",
  "Ferizaj",
  "Fushë Kosovë",
  "Gjakovë",
  "Gjilan",
  "Graçanicë",
  "Han i Elezit",
  "Istog",
  "Junik",
  "Kaçanik",
  "Kamenicë",
  "Klinë",
  "Kllokot",
  "Leposaviq",
  "Lipjan",
  "Malishevë",
  "Mamushë",
  "Mitrovicë",
  "Mitrovicë e Veriut",
  "Novobërdë",
  "Obiliq",
  "Partesh",
  "Pejë",
  "Podujevë",
  "Prishtinë",
  "Prizren",
  "Rahovec",
  "Ranillug",
  "Skënderaj",
  "Shtime",
  "Shtërpcë",
  "Suharekë",
  "Viti",
  "Vushtrri",
  "Zubin Potok",
  "Zveçan",
];
